Repository HNIKT-Tjenesteutvikling-Systemutvikling/NixHNIKT, pull requests merged in 2023-08, with the labels that each got.

#14 fix intellij non imperative
  modules/home-manager/programs/develop/default.nix
  modules/home-manager/programs/develop/intellij.nix
  modules/home-manager/programs/develop/vscode.nix
Labels: enhancement

#15 rev intellij and fix update
  flake.nix
  modules/home-manager/programs/develop/default.nix
  modules/home-manager/programs/develop/intellij.nix
  update.sh
Labels: enhancement

#17 fix update script to follow new user
  scripts/homeInstall.sh
  update.sh
Labels: enhancement

#18 setting up new user
  flake.nix
  home/solheim/default.nix
  home/solheim/desktop/default.nix
  home/solheim/services/default.nix
  host/solheim/default.nix
  host/solheim/network.nix
  host/solheim/services/default.nix
  host/solheim/user.nix
Labels: enhancement

#20 Add settings for Sigurd
  flake.nix
  home/sigubrat/default.nix
Labels: enhancement

#19 update pr
  home/turbonaepskrel/default.nix
Labels: enhancement

#22 fix intellij build debug options
  host/common/services/default.nix
  host/common/services/mysql.nix
  modules/nixos/programs/intellij.nix
Labels: bug, enhancement

#23 update hm to build intellij and jdk
  flake.nix
  home/common/programs/default.nix
  home/common/programs/intellij.nix
  modules/nixos/programs/default.nix
  modules/nixos/programs/intellij.nix
Labels: bug

#24 fix intellij runtime args
  home/common/programs/intellij.nix
Labels: bug

#31 fix install script for device name
  install.sh
  scripts/setup.sh
Labels: enhancement

#36 fix nfc card reader
  hosts/system/default.nix
  hosts/system/neard.nix
  hosts/system/nfc.nix
Labels: enhancement

#41 fix printing and setup emacs (basic)
  home/home.nix
  home/programs/default.nix
  home/programs/emacs.nix
  hosts/configuration.nix
  hosts/system/desktop/gnome.nix
Labels: bug, enhancement
